name: BungeecordAutoConfig
version: ${project.version}
main: de.epsdev.bungeeautoserver.spigottest.Bungeeautoserver.BungeecordAutoConfig
load: STARTUP
commands:
  changeServer:
    description: Change your or another players current server.
    permission: bungee.changeserver

  changeInstance:
    description: Change your or another players current server to a specific instance.
    permission: bungee.changeserver

  getServerInfo:
    description: Returns information about a specific server type.
    permission: bungee.status

  closeserver:
    description: Closes the active server instance.
    permission: bungee.opencloseserver

  openserver:
    description: Opens the active server instance.
    permission: bungee.opencloseserver

  broadcast:
    description: Send an message to all active instances.
    permission: bungee.broadcast

  ban:
    description: Ban a player from the network for a specified time.
    permission: bungee.ban

  unban:
    description: Remove a players network-ban.
    permission: bungee.ban
    aliases:
      - pardon
      -
  uwu:
    description: Shows the current versions hash.

  save:
    permission: bungee.save
    description: Uploads the world to an FTPS server

  menu:
    aliases:
      - server
      - m
    description: Opens a server selection GUI